version: "3.9"
# this is the version of docker-compose syntax we use

# we need to define services required to run our services
services:
  # name of the app
  app:
    # we are going to build the docker file inside the current directory
    build:
      context: .
      args:
        - DEV=true
    # maps port 8000 our system into port 8000 of docker container
    ports:
      - "8000:8000"
    # map our directory app to docker containers app directory, any changes we make will reflect immediately
    volumes:
      - ./app:/app
    # this is the command to run to start the service but this can be overwritten when you run docker command 
    # if we dont specify the command during the docker-compose then it will use the command specified insider the docker-compose file
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
