# Generated by Django 3.2.25 on 2024-05-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240516_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='incredients',
            new_name='ingredients',
        ),
    ]
